-- Create orders table for payment tracking
create table if not exists orders (
  id bigint primary key generated by default as identity,
  order_id text not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount numeric not null,
  status text not null check (status in ('pending', 'completed', 'failed', 'cancelled')),
  payment_id text,
  items jsonb not null,
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  customer_address text not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Create index for faster queries
create index if not exists idx_orders_user_id on orders(user_id);
create index if not exists idx_orders_order_id on orders(order_id);
create index if not exists idx_orders_status on orders(status);

-- Enable RLS
alter table orders enable row level security;

-- Create RLS policy for users to view their own orders
create policy "Users can view their own orders"
  on orders for select
  using (auth.uid() = user_id);

-- Create RLS policy for service role to update orders
create policy "Service role can update orders"
  on orders for update
  to service_role
  using (true);
